module.exports = {
    good: [
        'wonderful',
        'delightful',
        'fabulous',
        'fantastic',
        'marvelous',
        'splendid',
        'glorious',
        'magnificent',
        'superb',
        'excellent',
        'amazing',
        'interresting',
        'intriguing',
        'cool',
        'astonishing',
        'astounding',
        'intriguing',
        'incredible',
        'remarkable',
        'fascinating',
        'terrific',
        'extraordinary',
        'awesome',
        'spectacular',
        'outstanding'
    ]
};