import { Keys } from './configs';

export const keys: Keys = {
	mongoURI: process.env.MONGO_URI ? process.env.MONGO_URI : '',
	stats_id: process.env.STATS_ID ? process.env.STATS_ID : '',
	id_eric_munch: process.env.ERIC_MUNCH_ID ? process.env.ERIC_MUNCH_ID : '',
	command_prefix: process.env.COMMAND_PREFIX ? process.env.COMMAND_PREFIX : '',
	role_admin: process.env.ADMIN_ROLE_ID ? process.env.ADMIN_ROLE_ID : '',
	role_prefect: process.env.PREFECT_ROLE ? process.env.PREFECT_ROLE : '',
	role_IT: process.env.HOGWARTS_IT ? process.env.HOGWARTS_IT : '',
	channel_recording: process.env.GENERAL_CHANNEL_ID ? process.env.GENERAL_CHANNEL_ID : '',
	channel_mod_talk: process.env.MOD_TALK_CHANNEL ? process.env.MOD_TALK_CHANNEL : '',
	channel_bot_talk: process.env.BOT_TALK_CHANNEL ? process.env.BOT_TALK_CHANNEL : '',
	channel_welcome: process.env.CHANNEL_WELCOME ? process.env.CHANNEL_WELCOME : '',
	channel_banned: process.env.CHANNEL_BANNED ? process.env.CHANNEL_BANNED : '',
	channel_voice_recording: process.env.CHANNEL_VOICE_RECORDING ? process.env.CHANNEL_VOICE_RECORDING : '',
	emoji_dumbly: 'https://telegramchannels.me/storage/stickers/boywholived/big_boywholived_17.png',
	emoji_snape: 'https://telegramchannels.me/storage/stickers/boywholived/big_boywholived_2.png',
	devito_height: 147, // in cm
	devito_weight: 48000, // in g
	channel_house_points: process.env.HOUSE_POINTS_CHANNEL ? process.env.HOUSE_POINTS_CHANNEL : '',
	channel_trophy_room: process.env.TROPHY_ROOM_CHANNEL ? process.env.TROPHY_ROOM_CHANNEL : '',
	guild_id: process.env.GUILD_ID ? process.env.GUILD_ID : '',
	role_gryffindor: process.env.GRYFFINDOR_ROLE ? process.env.GRYFFINDOR_ROLE : '',
	role_slytherin: process.env.SLYTHERIN_ROLE ? process.env.SLYTHERIN_ROLE : '',
	role_ravenclaw: process.env.RAVENCLAW_ROLE ? process.env.RAVENCLAW_ROLE : '',
	role_hufflepuff: process.env.HUFFLEPUFF_ROLE ? process.env.HUFFLEPUFF_ROLE : '',
	reactions_timer: process.env.REACTIONS_TIMER ? parseInt(process.env.REACTIONS_TIMER) : 60000,
	emoji_addpoints: ['👍', '👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
	emoji_removepoints: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿'],
	emojis_vote_yes: ['👍', '👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
	emojis_vote_no: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿'],
	emojis_negative_reactions: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿', '🤮', '🤢'],
	slytherin_points_multiplier: process.env.SLYTHERIN_MULT ? parseFloat(process.env.SLYTHERIN_MULT) : 1.0,
	ravenclaw_points_multiplier: process.env.RAVENCLAW_MULT ? parseFloat(process.env.RAVENCLAW_MULT) : 1.0,
	gryffindor_points_multiplier: process.env.GRYFFINDOR_MULT ? parseFloat(process.env.GRYFFINDOR_MULT) : 1.0,
	hufflepuff_points_multiplier: process.env.HUFFLEPUFF_MULT ? parseFloat(process.env.HUFFLEPUFF_MULT) : 1.0,
	points_likes: process.env.POINTS_LIKES ? parseInt(process.env.POINTS_LIKES) : 10,
	points_votes: process.env.POINTS_VOTES ? parseInt(process.env.POINTS_VOTES) : 10,
	felix_chance: process.env.FELIX_CHANCE ? parseFloat(process.env.FELIX_CHANCE) : -1,
	number_reactions: process.env.NUMBER_REACTIONS ? parseInt(process.env.NUMBER_REACTIONS) : 7,
	gif_peace: 'https://tenor.com/view/peace-disappear-vanish-gif-9727828',
	token: process.env.DISCORD_TOKEN ? process.env.DISCORD_TOKEN : ''
}