module.exports = {
	mongoURI: process.env.MONGO_URI,
	stats_id: process.env.STATS_ID,
	command_prefix: process.env.COMMAND_PREFIX,
	admin_role_id: process.env.ADMIN_ROLE_NAME,
	general_channel_id: process.env.GENERAL_CHANNEL_ID,
	binger_gif: 'https://media.giphy.com/media/JPsFUPp3vLS5q/giphy.gif',
	dumbly_emoji: 'https://telegramchannels.me/storage/stickers/boywholived/boywholived_17.png',
	lupin_emoji: 'https://telegramchannels.me/storage/stickers/boywholived/boywholived_44.png',
	snape_emoji: 'https://telegramchannels.me/storage/stickers/boywholived/boywholived_2.png',
	neville_emoji: 'https://telegramchannels.me/storage/stickers/boywholived/boywholived_19.png',
	height: 147, // in cm
	weight: 48, // in Kg
	house_points_channel: process.env.HOUSE_POINTS_CHANNEL,
	gryffindor_role: process.env.GRYFFINDOR_ROLE,
	slytherin_role: process.env.SLYTHERIN_ROLE,
	ravenclaw_role: process.env.RAVENCLAW_ROLE,
	hufflepuff_role: process.env.HUFFLEPUFF_ROLE,
	recording_delay: process.env.RECORDING_DELAY,
	message_chance: process.env.MESSAGE_CHANCE,
	emoji_addpoints: process.env.EMOJI_ADDPOINTS,
	emoji_removepoints: process.env.EMOJI_REMOVEPOINTS,
	tiff_id: process.env.TIFF_ID,
	megan_id: process.env.MEGAN_ID,
	katie_id: process.env.KATIE_ID,
	sarah_id: process.env.SARAH_ID,
	mia_id: process.env.MIA_ID,
	marchismo_id: process.env.MARCHISMO_ID,
	brandon_id: process.env.BRANDON_ID,
	vini_id: process.env.VINI_ID,
	token: process.env.DISCORD_TOKEN,
};