import { Keys } from './configs';

export const keys: Keys = {
	mongoURI: process.env.MONGO_URI ? process.env.MONGO_URI : '',
	stats_id: process.env.STATS_ID ? process.env.STATS_ID : '',
	id_eric_munch: process.env.ERIC_MUNCH_ID ? process.env.ERIC_MUNCH_ID : '',
	command_prefix: process.env.COMMAND_PREFIX ? process.env.COMMAND_PREFIX : '',
	channel_recording: process.env.GENERAL_CHANNEL_ID ? process.env.GENERAL_CHANNEL_ID : '',
	channel_mod_talk: process.env.MOD_TALK_CHANNEL ? process.env.MOD_TALK_CHANNEL : '',
	channel_bot_talk: process.env.BOT_TALK_CHANNEL ? process.env.BOT_TALK_CHANNEL : '',
	channel_banned: process.env.CHANNEL_BANNED ? process.env.CHANNEL_BANNED : '',
	channel_noticeboard: process.env.CHANNEL_NOTICE_BOARD ? process.env.CHANNEL_NOTICE_BOARD : '',
	channel_voice_recording: process.env.CHANNEL_VOICE_RECORDING ? process.env.CHANNEL_VOICE_RECORDING : '',
	channel_polls: process.env.CHANNEL_POLLS ? process.env.CHANNEL_POLLS : '',
	channel_house_points: process.env.HOUSE_POINTS_CHANNEL ? process.env.HOUSE_POINTS_CHANNEL : '',
	channel_trophy_room: process.env.TROPHY_ROOM_CHANNEL ? process.env.TROPHY_ROOM_CHANNEL : '',
	channel_wheezes: process.env.CHANNEL_WHEEZES ? process.env.CHANNEL_WHEEZES : '',
	channel_come_go: process.env.CHANNEL_COME_GO ? process.env.CHANNEL_COME_GO : '',
	channel_welcome: process.env.CHANNEL_WELCOME ? process.env.CHANNEL_WELCOME : '',
	channel_sorting: process.env.CHANNEL_SORTING ? process.env.CHANNEL_SORTING : '',
	emoji_wheeze: process.env.EMOJI_WHEEZE ? process.env.EMOJI_WHEEZE : '🥸',
	chaos: process.env.CHAOS ? parseInt(process.env.CHAOS) === 1 : false,
	emoji_addpoints: ['👍', '👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
	emoji_removepoints: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿'],
	emojis_vote_yes: ['👍', '👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
	emojis_vote_no: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿'],
	emojis_negative_reactions: ['👎', '👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿', '🤮', '🤢'],
	devito_height: 147, // in cm
	devito_weight: 48000, // in g
	document_slythern: process.env.DOCUMENT_SLYTHERIN ? process.env.DOCUMENT_SLYTHERIN : '',
	guild_id: process.env.GUILD_ID ? process.env.GUILD_ID : '',
	role_gryffindor: process.env.GRYFFINDOR_ROLE ? process.env.GRYFFINDOR_ROLE : '',
	role_slytherin: process.env.SLYTHERIN_ROLE ? process.env.SLYTHERIN_ROLE : '',
	role_ravenclaw: process.env.RAVENCLAW_ROLE ? process.env.RAVENCLAW_ROLE : '',
	role_hufflepuff: process.env.HUFFLEPUFF_ROLE ? process.env.HUFFLEPUFF_ROLE : '',
	role_phoenix: process.env.ROLE_PHOENIX ? process.env.ROLE_PHOENIX : '',
	role_patron: process.env.ROLE_PATRON ? process.env.ROLE_PATRON : '',
	role_phoenix_plus: process.env.ROLE_PHOENIX_PLUS ? process.env.ROLE_PHOENIX_PLUS : '',
	role_phoenix_emoji: process.env.ROLE_PHOENIX_EMOJI ? process.env.ROLE_PHOENIX_EMOJI : '',
	role_ageline: process.env.ROLE_AGELINE ? process.env.ROLE_AGELINE : '',
	role_admin: process.env.ADMIN_ROLE_ID ? process.env.ADMIN_ROLE_ID : '',
	role_prefect: process.env.PREFECT_ROLE ? process.env.PREFECT_ROLE : '',
	role_IT: process.env.HOGWARTS_IT ? process.env.HOGWARTS_IT : '',
	role_helper_gryffindor: process.env.ROLE_HELPER_GRYFFINDOR ? process.env.ROLE_HELPER_GRYFFINDOR : '',
	role_helper_slytherin: process.env.ROLE_HELPER_SLYTHERIN ? process.env.ROLE_HELPER_SLYTHERIN : '',
	role_helper_ravenclaw: process.env.ROLE_HELPER_RAVENCLAW ? process.env.ROLE_HELPER_RAVENCLAW : '',
	role_helper_hufflepuff: process.env.ROLE_HELPER_HUFFLEPUFF ? process.env.ROLE_HELPER_HUFFLEPUFF : '',
	slytherin_points_multiplier: process.env.SLYTHERIN_MULT ? parseFloat(process.env.SLYTHERIN_MULT) : 1.0,
	slytherin_felix_chance: process.env.SLYTHERIN_FELIX_CHANCE ? parseFloat(process.env.SLYTHERIN_FELIX_CHANCE) : -1,
	ravenclaw_points_multiplier: process.env.RAVENCLAW_MULT ? parseFloat(process.env.RAVENCLAW_MULT) : 1.0,
	ravenclaw_felix_chance: process.env.RAVENCLAW_FELIX_CHANCE ? parseFloat(process.env.RAVENCLAW_FELIX_CHANCE) : -1,
	gryffindor_points_multiplier: process.env.GRYFFINDOR_MULT ? parseFloat(process.env.GRYFFINDOR_MULT) : 1.0,
	gryffindor_felix_chance: process.env.GRYFFINDOR_FELIX_CHANCE ? parseFloat(process.env.GRYFFINDOR_FELIX_CHANCE) : -1,
	hufflepuff_points_multiplier: process.env.HUFFLEPUFF_MULT ? parseFloat(process.env.HUFFLEPUFF_MULT) : 1.0,
	hufflepuff_felix_chance: process.env.HUFFLEPUFF_FELIX_CHANCE ? parseFloat(process.env.HUFFLEPUFF_FELIX_CHANCE) : -1,
	points_likes: process.env.POINTS_LIKES ? parseInt(process.env.POINTS_LIKES) : 10,
	points_zap_votes: process.env.POINTS_ZAP_VOTES ? parseInt(process.env.POINTS_ZAP_VOTES) : 10,
	points_votes: process.env.POINTS_VOTES ? parseInt(process.env.POINTS_VOTES) : 3,
	number_reactions: process.env.NUMBER_REACTIONS ? parseInt(process.env.NUMBER_REACTIONS) : 7,
	gif_peace: 'https://tenor.com/view/peace-disappear-vanish-gif-9727828',
	token: process.env.DISCORD_TOKEN ? process.env.DISCORD_TOKEN : ''
}